[2024-01-28T18:11:33.028+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_n_backfill_v0.task1 scheduled__2024-01-23T00:00:00+00:00 [queued]>
[2024-01-28T18:11:33.038+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_n_backfill_v0.task1 scheduled__2024-01-23T00:00:00+00:00 [queued]>
[2024-01-28T18:11:33.040+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-28T18:11:33.064+0530] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): task1> on 2024-01-23 00:00:00+00:00
[2024-01-28T18:11:33.068+0530] {standard_task_runner.py:60} INFO - Started process 4518 to run task
[2024-01-28T18:11:33.070+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_catchup_n_backfill_v0', 'task1', 'scheduled__2024-01-23T00:00:00+00:00', '--job-id', '318', '--raw', '--subdir', 'DAGS_FOLDER/4-create-dag-with-catchup_n_backfill.py', '--cfg-path', '/tmp/tmpsaqcmaep']
[2024-01-28T18:11:33.072+0530] {standard_task_runner.py:88} INFO - Job 318: Subtask task1
[2024-01-28T18:11:33.120+0530] {task_command.py:423} INFO - Running <TaskInstance: dag_with_catchup_n_backfill_v0.task1 scheduled__2024-01-23T00:00:00+00:00 [running]> on host mh1.myguest.virtualbox.org
[2024-01-28T18:11:33.216+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='hdu' AIRFLOW_CTX_DAG_ID='dag_with_catchup_n_backfill_v0' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-01-23T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-23T00:00:00+00:00'
[2024-01-28T18:11:33.217+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-28T18:11:33.218+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo testing']
[2024-01-28T18:11:33.223+0530] {subprocess.py:86} INFO - Output:
[2024-01-28T18:11:33.224+0530] {subprocess.py:93} INFO - testing
[2024-01-28T18:11:33.225+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-28T18:11:33.253+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_n_backfill_v0, task_id=task1, execution_date=20240123T000000, start_date=20240128T124133, end_date=20240128T124133
[2024-01-28T18:11:33.289+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-28T18:11:33.303+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
