[2024-01-28T18:11:17.031+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_n_backfill_v0.task1 scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-01-28T18:11:17.040+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_n_backfill_v0.task1 scheduled__2024-01-19T00:00:00+00:00 [queued]>
[2024-01-28T18:11:17.040+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-28T18:11:17.067+0530] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): task1> on 2024-01-19 00:00:00+00:00
[2024-01-28T18:11:17.069+0530] {standard_task_runner.py:60} INFO - Started process 4502 to run task
[2024-01-28T18:11:17.072+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_catchup_n_backfill_v0', 'task1', 'scheduled__2024-01-19T00:00:00+00:00', '--job-id', '314', '--raw', '--subdir', 'DAGS_FOLDER/4-create-dag-with-catchup_n_backfill.py', '--cfg-path', '/tmp/tmpoxal3n9i']
[2024-01-28T18:11:17.075+0530] {standard_task_runner.py:88} INFO - Job 314: Subtask task1
[2024-01-28T18:11:17.122+0530] {task_command.py:423} INFO - Running <TaskInstance: dag_with_catchup_n_backfill_v0.task1 scheduled__2024-01-19T00:00:00+00:00 [running]> on host mh1.myguest.virtualbox.org
[2024-01-28T18:11:17.211+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='hdu' AIRFLOW_CTX_DAG_ID='dag_with_catchup_n_backfill_v0' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-01-19T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-01-19T00:00:00+00:00'
[2024-01-28T18:11:17.213+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-28T18:11:17.214+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo testing']
[2024-01-28T18:11:17.221+0530] {subprocess.py:86} INFO - Output:
[2024-01-28T18:11:17.222+0530] {subprocess.py:93} INFO - testing
[2024-01-28T18:11:17.222+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-28T18:11:17.248+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_n_backfill_v0, task_id=task1, execution_date=20240119T000000, start_date=20240128T124117, end_date=20240128T124117
[2024-01-28T18:11:17.290+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-28T18:11:17.305+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
