[2024-01-28T18:18:30.004+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dag_with_catchup_n_backfill_v3.task1 manual__2024-01-28T12:48:25.700799+00:00 [queued]>
[2024-01-28T18:18:30.016+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dag_with_catchup_n_backfill_v3.task1 manual__2024-01-28T12:48:25.700799+00:00 [queued]>
[2024-01-28T18:18:30.016+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-28T18:18:30.046+0530] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): task1> on 2024-01-28 12:48:25.700799+00:00
[2024-01-28T18:18:30.049+0530] {standard_task_runner.py:60} INFO - Started process 4670 to run task
[2024-01-28T18:18:30.052+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'dag_with_catchup_n_backfill_v3', 'task1', 'manual__2024-01-28T12:48:25.700799+00:00', '--job-id', '325', '--raw', '--subdir', 'DAGS_FOLDER/4-create-dag-with-catchup_n_backfill.py', '--cfg-path', '/tmp/tmpws81z46d']
[2024-01-28T18:18:30.054+0530] {standard_task_runner.py:88} INFO - Job 325: Subtask task1
[2024-01-28T18:18:30.108+0530] {task_command.py:423} INFO - Running <TaskInstance: dag_with_catchup_n_backfill_v3.task1 manual__2024-01-28T12:48:25.700799+00:00 [running]> on host mh1.myguest.virtualbox.org
[2024-01-28T18:18:30.193+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='hdu' AIRFLOW_CTX_DAG_ID='dag_with_catchup_n_backfill_v3' AIRFLOW_CTX_TASK_ID='task1' AIRFLOW_CTX_EXECUTION_DATE='2024-01-28T12:48:25.700799+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-28T12:48:25.700799+00:00'
[2024-01-28T18:18:30.195+0530] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-01-28T18:18:30.196+0530] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'echo testing']
[2024-01-28T18:18:30.203+0530] {subprocess.py:86} INFO - Output:
[2024-01-28T18:18:30.203+0530] {subprocess.py:93} INFO - testing
[2024-01-28T18:18:30.203+0530] {subprocess.py:97} INFO - Command exited with return code 0
[2024-01-28T18:18:30.230+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=dag_with_catchup_n_backfill_v3, task_id=task1, execution_date=20240128T124825, start_date=20240128T124830, end_date=20240128T124830
[2024-01-28T18:18:30.269+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-28T18:18:30.284+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
